version: '3'

services:
  
  #MYSQL
  db:
    build:
      context: ./docker/db
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/db/.data:/var/lib/mysql
    networks:
      - app-network
  
  #PHP
  php-fpm:
    container_name: tennis-challenge_php-fpm_8-1
    build:
      context: ./docker/php-fpm
    depends_on:
      - db
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #SERVER
  nginx:
    build:
      context: ./docker/nginx
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
